### ISSUE TITLE
sklearn is deprecated

### ISSUE THREAD

**Issue by JacobPFrick** [BojarLab/glycowork#61] opened 2024-10-09 17:42 UTC
###I am trying to install glycowork and running into an issue with sklearn deprecation compatibility issues.

Collecting sklearn (from glycowork[all])
  Using cached sklearn-0.0.post12.tar.gz (2.6 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.
     
      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
     
      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-package
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by Bribak** [comment] 2024-10-09 17:54
Hi & thanks!

I checked our requirements file and we correctly specify `scikit-learn`, so it might be one of our dependencies that's still relying on `sklearn`.

You're doing a pip install of the current version (1.3)?
And could you report back whether the "standard" install (so not specifying [all]) works? I did that successfully a couple of weeks ago on a fresh laptop, so would be interesting to know whether it's something in the additional dependencies

**Comment by JacobPFrick** [comment] 2024-10-09 18:06
Thanks for the quick response!
Yes, pip install of the current glycowork[all].
Install of the standard "glycowork" works. I also don't get this error when doing the glycowork[ml] which has what I need to use the LectinOracle module.

**Comment by Bribak** [comment] 2024-10-09 18:12
Thanks for the additional info that's great; Looking at the intersection of dependencies that could cause the issue, it could be that this is something that will be fixed with a glyles update soon (@Old-Shatterhand ), since we know that this can currently cause install issues. Will keep this open until we've resolved this

**Comment by JacobPFrick** [comment] 2024-10-10 23:02
Thank you!

**Comment by Old-Shatterhand** [comment] 2024-10-15 14:09
Hi @JacobPFrick,

I just installed `glycowork[all]` into an empty conda environment with Python v3.9 and couldn't reproduce your issue. There are some reasons for this observation:

- Do you use glycowork with other packages in the same environment? That could cause dependency clashes and pip might fall back to older versions.
- Which Python version are you using? In package builds for older Python versions, `pip install sklearn` may be specified, which might have been updated since.

If neither of these apply to your case:

- Have you tried to reinstall everything into a new, empty environment?
- May I ask you to upload the full commandline output starting from your `pip install glycowork[all]` command?

Best, Roman

**Comment by Bribak** [comment] 2024-10-24 09:26
Closing this for now as stale, since it seems to work in a fresh environment and the mentioned `glyles` issue has been resolved as well

**Closed by Bribak** 2024-10-24 09:26 UTC
