### ISSUE TITLE
Mysterious error in get_differential_expression() "Cannot index with multidimensional key"

### ISSUE THREAD

**Issue by mattias-erhardsson** [BojarLab/glycowork#52] opened 2024-06-27 11:12 UTC
When running a similar example as issue #51, there's a mysterious error "Cannot index with multidimensional key". Running the dev branch.

```
import pandas as pd
from glycowork.motif.analysis import get_differential_expression
from glycowork.motif.analysis import get_volcano
from glycowork.motif.draw import annotate_figure
from glycowork.motif.draw import GlycoDraw
```

```
data = {
    'Glycan': ['Gal(b1-3)GalNAc', 'GalOS(b1-3)GalNAc', 'Gal(b1-3)[Fuc(a1-?)]GalNAc', 'GlcNAc(b1-2)Man(a1-3)Man', 'Man(a1-6)[Man(a1-3)]Man(b1-4)GlcNAc(b1-4)GlcNAc', 'Neu5Ac(a2-6)Gal(b1-4)GlcNAc(b1-2)Man', 'Neu5Ac(a2-3)Gal(b1-3)GalNAc'],
    'Sample1': [1.1, 0.2, 0.3, 0.5, 0.7, 1.0, 0.6],
    'Sample2': [1.2, 0.1, 0.2, 0.4, 0.8, 0.9, 0.5],
    'Sample3': [0.1, 1.8, 1.9, 0.3, 0.6, 0.8, 1.2],
    'Sample4': [0.2, 1.1, 1.2, 0.2, 0.5, 0.7, 1.1],
    'Sample5': [1.3, 0.3, 0.4, 0.6, 0.9, 1.1, 0.7],
    'Sample6': [1.4, 0.4, 0.5, 0.7, 1.0, 1.2, 0.8],
    'Sample7': [0.3, 1.9, 2.0, 0.4, 0.7, 0.9, 1.3],
    'Sample8': [0.4, 1.2, 1.3, 0.3, 0.6, 0.8, 1.2]
}
differential_glycomics_df = pd.DataFrame(data)

# Define the groups
group1 = ['Sample1', 'Sample2', 'Sample5', 'Sample6']
group2 = ['Sample3', 'Sample4', 'Sample7', 'Sample8']

differential_expression = get_differential_expression(df = differential_glycomics_df,
                            group1 = group1,
                            group2 = group2,
                            motifs = True,
                            feature_set = ['terminal1'],
                            paired = False,
                            min_samples = 0.1)

print(differential_expression)
```

**Comment by Bribak** [comment] 2024-06-27 12:23
Ohh I just played around with this and the issue is that the correct feature_set term would be 'terminal' (a bit legacy, since we started with 'terminal'). So quantify_motifs returned an empty dataframe because no feature_set was recognized and that caused issues

I've now:
- made sure that both 'terminal' and 'terminal1' can be used
- produce an informative error message if a term is used in feature_set that is not recognized

It's fixed with 3098e80

Great that you bring up these points! Makes everything more robust:-)

**Closed by Bribak** 2024-06-27 12:23 UTC
